### ISSUE TITLE
[PE-D] exit command accepts random args where there should be non

### ISSUE THREAD

**Issue by nus-se-script** [AY2122S2-TIC4002-F18-5/tp2#113] opened 2022-03-26 16:45 UTC
exit command accepts random args like list command.

-------------
Labels: `type.FeatureFlaw` `severity.Medium`
original: gweeyc/ped#10

**Comment by gweeyc** [comment] 2022-03-31 08:27
Not a bug, according to UG -> Features notes, the App is programmed to behave as defined below:
- Extraneous parameters for commands that do not take in parameters (such as help, list, exit and clear) will be ignored.
e.g. if the command specifies help 123, it will be interpreted as help.

**Closed by gweeyc** 2022-03-31 08:27 UTC
